name: flutter_notification_queue
description: "An overlay based In App Notification"
version: 0.4.0
repository: https://github.com/pooriaaskarim/flutter_notification_queue
topics: [ flutter, notification, overlay, toast, popup ]
license: BSD-3-Clause

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logd: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
